# Generated by Django 4.2.13 on 2024-07-14 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=20)),
                ('c_desc', models.TextField()),
                ('c_image', models.ImageField(blank=True, null=True, upload_to='media/image')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=20)),
                ('p_desc', models.TextField()),
                ('p_price', models.IntegerField()),
                ('p_image', models.ImageField(blank=True, null=True, upload_to='media/products')),
                ('p_stock', models.IntegerField()),
                ('p_available', models.BooleanField(default=True)),
                ('p_created', models.DateTimeField(auto_now_add=True)),
                ('p_updated', models.DateTimeField(auto_now=True)),
                ('p_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.category')),
            ],
        ),
    ]
